### ISSUE TITLE
Add ESLint?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search#239]
Somehow I _just_ noticed that we don't seem to have any ESLint in this repo.

Let me know if we're interested and I can throw together a PR and then we can argue about what rules we want to use.

Here's a hacky first attempt at some rules/globals and silencing some annoying errors (ie: `EXPORTED_SYMBOLS` is defined but never used):

``` yaml
extends:
  - eslint:recommended

env:
  es6: true
  browser: true

globals:
  ADDON_DISABLE: false
  ADDON_ENABLE: false
  ADDON_INSTALL: false
  ADDON_UNINSTALL: false
  APP_SHUTDOWN: false
  Components: false
  CustomizableUI: false
  ObjectUtils: false
  PrivateBrowsingUtils: false
  Services: false
  XPCOMUtils: false

rules:
  no-console: 1
  no-unused-vars: [2, {vars: all, args: none, varsIgnorePattern: "install|uninstall|startup|shutdown|EXPORTED_SYMBOLS"}]
```

Currently this is giving me ~10 errors and 5 warnings (but I haven't sprinkled in any `// eslint-disable-line ${rule}` yet.

``` sh
$ eslint .

/Users/pdehaan/dev/github/mozilla/universal-search/bootstrap.js
  19:3  error  'UniversalSearch' is not defined  no-undef
  33:3  error  'UniversalSearch' is not defined  no-undef

/Users/pdehaan/dev/github/mozilla/universal-search/lib/ui/recommendation-row.js
  98:32  error  'defaultFavicon' is not defined  no-undef

/Users/pdehaan/dev/github/mozilla/universal-search/lib/ui/recommendation.js
  197:13  error  'container' is defined but never used    no-unused-vars
  275:9   error  'isDuplicate' is defined but never used  no-unused-vars
  365:20  error  Empty block statement                    no-empty

/Users/pdehaan/dev/github/mozilla/universal-search/lib/universal-search.js
   39:5  error    'WindowWatcher' is not defined               no-undef
   43:5  error    'WindowWatcher' is not defined               no-undef
   47:5  warning  Unexpected console statement                 no-console
   59:5  warning  Unexpected console statement                 no-console
   63:5  warning  Unexpected console statement                 no-console
   75:5  warning  Unexpected console statement                 no-console
  262:5  warning  Unexpected console statement                 no-console
  267:7  error    'UniversalSearch' is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/mozilla/universal-search/lib/window-watcher.js
  111:7  error  'WindowWatcher' is defined but never used  no-unused-vars

✖ 15 problems (10 errors, 5 warnings)
```
